name = "test widget with all values"
width = 900
height = 500
color = "#ffffff96"
position = [1000, 150]

[[tool]]
tool_type = "Button"
color = "#000000ff"
shape = [
    500, 50,
    800, 400
]
action = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"