name = "test widget with all values"
width = 900
height = 500
color = "#00000096"
position = [50, 50]

[[shape]]
shape_type = "Triangle"
color = "#ffffffff"
shape = [
    50, 50, 
    250, 250, 
    450, 50
]

[[shape]]
shape_type = "Triangle"
color = "#ffffffff"
shape = [
    50, 450,
    250, 250,
    450, 450
]

[[shape]]
shape_type = "Rectangle"
color = "#ffffffff"
shape = [
    500, 50,
    300, 300
]