name = "test widget with all values"
width = 900
height = 500
color = "#00000096"
position = [50, 50]

[[shape]]
name = "test triangle"
shape_type = "Triangle"
color = "#ffffffff"
shape = [
    50, 50, 
    250, 250, 
    400, 50
]

[[shape]]
name = "test triangle"
shape_type = "Triangle"
color = "#ffffffff"
shape = [
    50, 400,
    300, 300,
    400, 400
]

[[shape]]
name = "test triangle"
shape_type = "Rectangle"
color = "#ffffffff"
shape = [
    500, 50,
    800, 400
]