name = "test widget with all values"
width = 900
height = 500
color = "#ffffff96"
position = [1000, 150]

[[tool]]
ty = "Button"
color = "#000000ff"
shape = [
    1, 1,
    899, 499
]
action = { action = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe", ty = "Clicked" }